package org.ami.sancionatorios;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "area")
public class Area implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.SEQUENCE, generator = "AREA_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(allocationSize = 1, sequenceName = "area_idarea_seq", name = "AREA_ID_GENERATOR")
   @org.kie.api.definition.type.Description("id area")
   private java.lang.Long idarea;

   @org.kie.api.definition.type.Label("nombrearea")
   private java.lang.String nombrearea;

   public Area()
   {
   }

   public java.lang.Long getIdarea()
   {
      return this.idarea;
   }

   public void setIdarea(java.lang.Long idarea)
   {
      this.idarea = idarea;
   }

   public java.lang.String getNombrearea()
   {
      return this.nombrearea;
   }

   public void setNombrearea(java.lang.String nombrearea)
   {
      this.nombrearea = nombrearea;
   }

   public String toString()
   {
      return "[nombrearea= " + this.nombrearea + " - idarea= " + this.idarea + "]";
   }

   public Area(java.lang.Long idarea, java.lang.String nombrearea)
   {
      this.idarea = idarea;
      this.nombrearea = nombrearea;
   }

}