package org.ami.sancionatorios;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "expediente")
public class Expediente implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("numero expediente ")
   private java.lang.Long numeroexpediente;
   @org.kie.api.definition.type.Label("identificador del area")
   private java.lang.Long idarea;
   @org.kie.api.definition.type.Label("identificador del tipo de queja")
   private java.lang.Long idtipoqueja;
   @org.kie.api.definition.type.Label("identificador del ambito de la queja")
   private java.lang.Long idambitoqueja;
   @org.kie.api.definition.type.Label("consecutivo asociado al expediente")
   private java.lang.Long consecutivo;
   @org.kie.api.definition.type.Label("identificador de la norma que aplica")
   private java.lang.Long idnorma;
   @org.kie.api.definition.type.Label("identificador del estrato")
   @javax.persistence.JoinColumn(name = "idestrato")
   @javax.persistence.ManyToOne(optional = false, fetch = javax.persistence.FetchType.LAZY, cascade = { javax.persistence.CascadeType.ALL })
   private Estrato idestrato;

   @org.kie.api.definition.type.Label("identificador de la localidad")
   private java.lang.Long idlocalidad;

   @org.kie.api.definition.type.Label("fecha de la caducidad ")
   private java.util.Date fechacaducidad;

   @org.kie.api.definition.type.Label("fecha de la radicacion de la queja")
   private java.util.Date fecharadicacion;

   @org.kie.api.definition.type.Label("proyecto de vivienda sobre la que se interpone la queja")
   private java.lang.String proyectovivienda;

   @org.kie.api.definition.type.Label("direccion del proyecto de vivienda relacionada con la queja")
   private java.lang.String direccionproyectovivienda;

   @org.kie.api.definition.type.Label("identificacdor del quejoso")
   private java.lang.Long idquejoso;

   @org.kie.api.definition.type.Label("identificador del inicio del tipo de actuacion de la queja")
   private java.lang.Long idtipoiniactuacion;

   @org.kie.api.definition.type.Label("radicado del inicio de la actuacion enviada al investigado")
   private java.lang.String radinicioactuacioninv;

   @org.kie.api.definition.type.Label("fecha del radicado del inicio de la actuacion al investigado")
   private java.util.Date fecharadinicioactuacioninv;

   @org.kie.api.definition.type.Label("radicado del inicio de la actuacion del quejoso")
   private java.lang.String radinicioactuacionque;

   @org.kie.api.definition.type.Label("fecha del radicado del inicio de la actuacion al quejoso")
   private java.util.Date fecharadinicioactuacionque;

   @org.kie.api.definition.type.Label("identificador de la fase tecnica")
   private java.lang.Long idfasetecnica;

   @org.kie.api.definition.type.Label("consecutivo de la tabla padre")
   private java.lang.Long consecutivo_padre;

   @org.kie.api.definition.type.Label("identificador del investigado")
   private java.lang.Long idinvestigado;

   @org.kie.api.definition.type.Label("fecha de entrega del area de despacho a notificaciones")
   private java.util.Date fechaentreganotificaciones;

   @org.kie.api.definition.type.Label("fecha de la constacia ejecutoria")
   private java.util.Date fechaejecutoria;

   @org.kie.api.definition.type.Label("fecha de perdida ejecutoria ")
   private java.util.Date fechaperdidaejecutoria;

   @org.kie.api.definition.type.Label("identificador del expediente")
   @javax.persistence.Id
   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.SEQUENCE, generator = "SECUENCIA_EXPEDIENTE")
   @javax.persistence.SequenceGenerator(allocationSize = 1, sequenceName = "expediente_idexpediente_seq", name = "SECUENCIA_EXPEDIENTE")
   private java.lang.Long idexpediente;

   public Expediente()
   {
   }

   public java.lang.Long getNumeroexpediente()
   {
      return this.numeroexpediente;
   }

   public void setNumeroexpediente(java.lang.Long numeroexpediente)
   {
      this.numeroexpediente = numeroexpediente;
   }

   public java.lang.Long getIdarea()
   {
      return this.idarea;
   }

   public void setIdarea(java.lang.Long idarea)
   {
      this.idarea = idarea;
   }

   public java.lang.Long getIdtipoqueja()
   {
      return this.idtipoqueja;
   }

   public void setIdtipoqueja(java.lang.Long idtipoqueja)
   {
      this.idtipoqueja = idtipoqueja;
   }

   public java.lang.Long getIdambitoqueja()
   {
      return this.idambitoqueja;
   }

   public void setIdambitoqueja(java.lang.Long idambitoqueja)
   {
      this.idambitoqueja = idambitoqueja;
   }

   public java.lang.Long getConsecutivo()
   {
      return this.consecutivo;
   }

   public void setConsecutivo(java.lang.Long consecutivo)
   {
      this.consecutivo = consecutivo;
   }

   public java.lang.Long getIdnorma()
   {
      return this.idnorma;
   }

   public void setIdnorma(java.lang.Long idnorma)
   {
      this.idnorma = idnorma;
   }

   public java.lang.Long getIdlocalidad()
   {
      return this.idlocalidad;
   }

   public void setIdlocalidad(java.lang.Long idlocalidad)
   {
      this.idlocalidad = idlocalidad;
   }

   public java.util.Date getFechacaducidad()
   {
      return this.fechacaducidad;
   }

   public void setFechacaducidad(java.util.Date fechacaducidad)
   {
      this.fechacaducidad = fechacaducidad;
   }

   public java.util.Date getFecharadicacion()
   {
      return this.fecharadicacion;
   }

   public void setFecharadicacion(java.util.Date fecharadicacion)
   {
      this.fecharadicacion = fecharadicacion;
   }

   public java.lang.String getProyectovivienda()
   {
      return this.proyectovivienda;
   }

   public void setProyectovivienda(java.lang.String proyectovivienda)
   {
      this.proyectovivienda = proyectovivienda;
   }

   public java.lang.String getDireccionproyectovivienda()
   {
      return this.direccionproyectovivienda;
   }

   public void setDireccionproyectovivienda(
         java.lang.String direccionproyectovivienda)
   {
      this.direccionproyectovivienda = direccionproyectovivienda;
   }

   public java.lang.Long getIdquejoso()
   {
      return this.idquejoso;
   }

   public void setIdquejoso(java.lang.Long idquejoso)
   {
      this.idquejoso = idquejoso;
   }

   public java.lang.Long getIdtipoiniactuacion()
   {
      return this.idtipoiniactuacion;
   }

   public void setIdtipoiniactuacion(java.lang.Long idtipoiniactuacion)
   {
      this.idtipoiniactuacion = idtipoiniactuacion;
   }

   public java.lang.String getRadinicioactuacioninv()
   {
      return this.radinicioactuacioninv;
   }

   public void setRadinicioactuacioninv(java.lang.String radinicioactuacioninv)
   {
      this.radinicioactuacioninv = radinicioactuacioninv;
   }

   public java.util.Date getFecharadinicioactuacioninv()
   {
      return this.fecharadinicioactuacioninv;
   }

   public void setFecharadinicioactuacioninv(
         java.util.Date fecharadinicioactuacioninv)
   {
      this.fecharadinicioactuacioninv = fecharadinicioactuacioninv;
   }

   public java.lang.String getRadinicioactuacionque()
   {
      return this.radinicioactuacionque;
   }

   public void setRadinicioactuacionque(java.lang.String radinicioactuacionque)
   {
      this.radinicioactuacionque = radinicioactuacionque;
   }

   public java.util.Date getFecharadinicioactuacionque()
   {
      return this.fecharadinicioactuacionque;
   }

   public void setFecharadinicioactuacionque(
         java.util.Date fecharadinicioactuacionque)
   {
      this.fecharadinicioactuacionque = fecharadinicioactuacionque;
   }

   public java.lang.Long getIdfasetecnica()
   {
      return this.idfasetecnica;
   }

   public void setIdfasetecnica(java.lang.Long idfasetecnica)
   {
      this.idfasetecnica = idfasetecnica;
   }

   public java.lang.Long getConsecutivo_padre()
   {
      return this.consecutivo_padre;
   }

   public void setConsecutivo_padre(java.lang.Long consecutivo_padre)
   {
      this.consecutivo_padre = consecutivo_padre;
   }

   public java.lang.Long getIdinvestigado()
   {
      return this.idinvestigado;
   }

   public void setIdinvestigado(java.lang.Long idinvestigado)
   {
      this.idinvestigado = idinvestigado;
   }

   public java.util.Date getFechaentreganotificaciones()
   {
      return this.fechaentreganotificaciones;
   }

   public void setFechaentreganotificaciones(
         java.util.Date fechaentreganotificaciones)
   {
      this.fechaentreganotificaciones = fechaentreganotificaciones;
   }

   public java.util.Date getFechaejecutoria()
   {
      return this.fechaejecutoria;
   }

   public void setFechaejecutoria(java.util.Date fechaejecutoria)
   {
      this.fechaejecutoria = fechaejecutoria;
   }

   public java.util.Date getFechaperdidaejecutoria()
   {
      return this.fechaperdidaejecutoria;
   }

   public void setFechaperdidaejecutoria(java.util.Date fechaperdidaejecutoria)
   {
      this.fechaperdidaejecutoria = fechaperdidaejecutoria;
   }

   public java.lang.Long getIdexpediente()
   {
      return this.idexpediente;
   }

   public void setIdexpediente(java.lang.Long idexpediente)
   {
      this.idexpediente = idexpediente;
   }

   public org.ami.sancionatorios.Estrato getIdestrato()
   {
      return this.idestrato;
   }

   public void setIdestrato(org.ami.sancionatorios.Estrato idestrato)
   {
      this.idestrato = idestrato;
   }

   public Expediente(java.lang.Long numeroexpediente, java.lang.Long idarea,
         java.lang.Long idtipoqueja, java.lang.Long idambitoqueja,
         java.lang.Long consecutivo, java.lang.Long idnorma,
         org.ami.sancionatorios.Estrato idestrato, java.lang.Long idlocalidad,
         java.util.Date fechacaducidad, java.util.Date fecharadicacion,
         java.lang.String proyectovivienda,
         java.lang.String direccionproyectovivienda, java.lang.Long idquejoso,
         java.lang.Long idtipoiniactuacion,
         java.lang.String radinicioactuacioninv,
         java.util.Date fecharadinicioactuacioninv,
         java.lang.String radinicioactuacionque,
         java.util.Date fecharadinicioactuacionque,
         java.lang.Long idfasetecnica, java.lang.Long consecutivo_padre,
         java.lang.Long idinvestigado,
         java.util.Date fechaentreganotificaciones,
         java.util.Date fechaejecutoria, java.util.Date fechaperdidaejecutoria,
         java.lang.Long idexpediente)
   {
      this.numeroexpediente = numeroexpediente;
      this.idarea = idarea;
      this.idtipoqueja = idtipoqueja;
      this.idambitoqueja = idambitoqueja;
      this.consecutivo = consecutivo;
      this.idnorma = idnorma;
      this.idestrato = idestrato;
      this.idlocalidad = idlocalidad;
      this.fechacaducidad = fechacaducidad;
      this.fecharadicacion = fecharadicacion;
      this.proyectovivienda = proyectovivienda;
      this.direccionproyectovivienda = direccionproyectovivienda;
      this.idquejoso = idquejoso;
      this.idtipoiniactuacion = idtipoiniactuacion;
      this.radinicioactuacioninv = radinicioactuacioninv;
      this.fecharadinicioactuacioninv = fecharadinicioactuacioninv;
      this.radinicioactuacionque = radinicioactuacionque;
      this.fecharadinicioactuacionque = fecharadinicioactuacionque;
      this.idfasetecnica = idfasetecnica;
      this.consecutivo_padre = consecutivo_padre;
      this.idinvestigado = idinvestigado;
      this.fechaentreganotificaciones = fechaentreganotificaciones;
      this.fechaejecutoria = fechaejecutoria;
      this.fechaperdidaejecutoria = fechaperdidaejecutoria;
      this.idexpediente = idexpediente;
   }

}