package org.ami.sancionatorios;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class FaseTecnica implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.SEQUENCE, generator = "FASETECNICA_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(allocationSize = 1, sequenceName = "estadotecnica_idestadotecnica_seq", name = "FASETECNICA_ID_GENERATOR")
   @org.kie.api.definition.type.Label(value = "identificador de la fase en tecnica")
   private java.lang.Long idfasetecnica;

   @org.kie.api.definition.type.Label(value = "nombre de fase en tecnica")
   private java.lang.String nombrefasetecnica;

   @org.kie.api.definition.type.Label(value = "identificador del area")
   private java.lang.Long idarea;

   public FaseTecnica()
   {
   }

   public java.lang.Long getIdfasetecnica()
   {
      return this.idfasetecnica;
   }

   public void setIdfasetecnica(java.lang.Long idfasetecnica)
   {
      this.idfasetecnica = idfasetecnica;
   }

   public java.lang.String getNombrefasetecnica()
   {
      return this.nombrefasetecnica;
   }

   public void setNombrefasetecnica(java.lang.String nombrefasetecnica)
   {
      this.nombrefasetecnica = nombrefasetecnica;
   }

   public java.lang.Long getIdarea()
   {
      return this.idarea;
   }

   public void setIdarea(java.lang.Long idarea)
   {
      this.idarea = idarea;
   }

   public String toString()
   {
      return "[nombrefasetecnica= " + this.nombrefasetecnica + " - idarea= " + this.idarea + " - idfasetecnica= " + this.idfasetecnica + "]";
   }

   public FaseTecnica(java.lang.Long idfasetecnica,
         java.lang.String nombrefasetecnica, java.lang.Long idarea)
   {
      this.idfasetecnica = idfasetecnica;
      this.nombrefasetecnica = nombrefasetecnica;
      this.idarea = idarea;
   }

}