package org.ami.sancionatorios;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Funcionario implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.SEQUENCE, generator = "FUNCIONARIO_ID_GENERATOR")
   @javax.persistence.Id
   @org.kie.api.definition.type.Label("identificacion del funcionario")
   @javax.persistence.SequenceGenerator(allocationSize = 1, sequenceName = "funcionario_idfuncionario_seq", name = "FUNCIONARIO_ID_GENERATOR")
   private java.lang.Long idfuncionario;

   @org.kie.api.definition.type.Label("nombre del funcionario responsable del proceso")
   private java.lang.String nombrefuncionario;

   @org.kie.api.definition.type.Label("documento de identidad del funcionario")
   private java.lang.String cedula;

   @org.kie.api.definition.type.Label("identificador del area")
   private java.lang.Long idarea;

   @org.kie.api.definition.type.Label("reconocimiento del contratista")
   private java.lang.Boolean contratista;

   public Funcionario()
   {
   }

   public java.lang.Long getIdfuncionario()
   {
      return this.idfuncionario;
   }

   public void setIdfuncionario(java.lang.Long idfuncionario)
   {
      this.idfuncionario = idfuncionario;
   }

   public java.lang.String getNombrefuncionario()
   {
      return this.nombrefuncionario;
   }

   public void setNombrefuncionario(java.lang.String nombrefuncionario)
   {
      this.nombrefuncionario = nombrefuncionario;
   }

   public java.lang.String getCedula()
   {
      return this.cedula;
   }

   public void setCedula(java.lang.String cedula)
   {
      this.cedula = cedula;
   }

   public java.lang.Long getIdarea()
   {
      return this.idarea;
   }

   public void setIdarea(java.lang.Long idarea)
   {
      this.idarea = idarea;
   }

   public java.lang.Boolean getContratista()
   {
      return this.contratista;
   }

   public void setContratista(java.lang.Boolean contratista)
   {
      this.contratista = contratista;
   }

   public Funcionario(java.lang.Long idfuncionario,
         java.lang.String nombrefuncionario, java.lang.String cedula,
         java.lang.Long idarea, java.lang.Boolean contratista)
   {
      this.idfuncionario = idfuncionario;
      this.nombrefuncionario = nombrefuncionario;
      this.cedula = cedula;
      this.idarea = idarea;
      this.contratista = contratista;
   }

}