package org.ami.sancionatorios;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Investigado implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "INVESTIGADO_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "INVESTIGADO_ID_SEQ", name = "INVESTIGADO_ID_GENERATOR")
   @org.kie.api.definition.type.Label("identificacion del investigado")
   private java.lang.Long idinvestigado;

   @org.kie.api.definition.type.Label("documento de identidad del investigado")
   private java.lang.String identificacion;

   @org.kie.api.definition.type.Label("nombre del investigado")
   private java.lang.String nombre;

   @org.kie.api.definition.type.Label("direccion del investigado")
   private java.lang.String direccion;

   @org.kie.api.definition.type.Label("correo electronico del investigado")
   private java.lang.String correoelectronico;

   @org.kie.api.definition.type.Label("numero del registro o matricula mercantil del investigado")
   private java.lang.String registro;

   @org.kie.api.definition.type.Label("identificacion de la autroizacion del uso del correo electronico")
   private java.lang.Boolean indautusocorreo;

   @org.kie.api.definition.type.Label("consecutivo del investigado")
   private java.lang.Long idexpediente;

   public Investigado()
   {
   }

   public java.lang.Long getIdinvestigado()
   {
      return this.idinvestigado;
   }

   public void setIdinvestigado(java.lang.Long idinvestigado)
   {
      this.idinvestigado = idinvestigado;
   }

   public java.lang.String getIdentificacion()
   {
      return this.identificacion;
   }

   public void setIdentificacion(java.lang.String identificacion)
   {
      this.identificacion = identificacion;
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public java.lang.String getDireccion()
   {
      return this.direccion;
   }

   public void setDireccion(java.lang.String direccion)
   {
      this.direccion = direccion;
   }

   public java.lang.String getCorreoelectronico()
   {
      return this.correoelectronico;
   }

   public void setCorreoelectronico(java.lang.String correoelectronico)
   {
      this.correoelectronico = correoelectronico;
   }

   public java.lang.String getRegistro()
   {
      return this.registro;
   }

   public void setRegistro(java.lang.String registro)
   {
      this.registro = registro;
   }

   public java.lang.Boolean getIndautusocorreo()
   {
      return this.indautusocorreo;
   }

   public void setIndautusocorreo(java.lang.Boolean indautusocorreo)
   {
      this.indautusocorreo = indautusocorreo;
   }

   public java.lang.Long getIdexpediente()
   {
      return this.idexpediente;
   }

   public void setIdexpediente(java.lang.Long idexpediente)
   {
      this.idexpediente = idexpediente;
   }

   public Investigado(java.lang.Long idinvestigado,
         java.lang.String identificacion, java.lang.String nombre,
         java.lang.String direccion, java.lang.String correoelectronico,
         java.lang.String registro, java.lang.Boolean indautusocorreo,
         java.lang.Long idexpediente)
   {
      this.idinvestigado = idinvestigado;
      this.identificacion = identificacion;
      this.nombre = nombre;
      this.direccion = direccion;
      this.correoelectronico = correoelectronico;
      this.registro = registro;
      this.indautusocorreo = indautusocorreo;
      this.idexpediente = idexpediente;
   }

}