package org.ami.sancionatorios;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Quejoso implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.SEQUENCE, generator = "QUEJOSO_ID_GENERATOR")
   @javax.persistence.Id
   @org.kie.api.definition.type.Label("identificador del quejoso")
   @javax.persistence.SequenceGenerator(allocationSize = 1, sequenceName = "quejoso_idquejoso_seq", name = "QUEJOSO_ID_GENERATOR")
   private java.lang.Long idquejoso;

   @org.kie.api.definition.type.Label("nombre del quejoso")
   private java.lang.String nombrequejoso;

   @org.kie.api.definition.type.Label("direccion del quejoso")
   private java.lang.String direccionquejoso;

   public Quejoso()
   {
   }

   public java.lang.Long getIdquejoso()
   {
      return this.idquejoso;
   }

   public void setIdquejoso(java.lang.Long idquejoso)
   {
      this.idquejoso = idquejoso;
   }

   public java.lang.String getNombrequejoso()
   {
      return this.nombrequejoso;
   }

   public void setNombrequejoso(java.lang.String nombrequejoso)
   {
      this.nombrequejoso = nombrequejoso;
   }

   public java.lang.String getDireccionquejoso()
   {
      return this.direccionquejoso;
   }

   public void setDireccionquejoso(java.lang.String direccionquejoso)
   {
      this.direccionquejoso = direccionquejoso;
   }

   public Quejoso(java.lang.Long idquejoso, java.lang.String nombrequejoso,
         java.lang.String direccionquejoso)
   {
      this.idquejoso = idquejoso;
      this.nombrequejoso = nombrequejoso;
      this.direccionquejoso = direccionquejoso;
   }

}