package org.ami.sancionatorios;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class TipoVisita implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.SEQUENCE, generator = "TIPOVISITA_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(allocationSize = 1, sequenceName = "tipovisita_idtipovisita_seq", name = "TIPOVISITA_ID_GENERATOR")
   @org.kie.api.definition.type.Label(value = "id tipo de visita")
   private java.lang.Long idtipovisita;

   @org.kie.api.definition.type.Label(value = "nombre del tipo de visita")
   private java.lang.String nombretipovisita;

   public TipoVisita()
   {
   }

   public java.lang.Long getIdtipovisita()
   {
      return this.idtipovisita;
   }

   public void setIdtipovisita(java.lang.Long idtipovisita)
   {
      this.idtipovisita = idtipovisita;
   }

   public java.lang.String getNombretipovisita()
   {
      return this.nombretipovisita;
   }
   
   public String toString()
   {
      return "[nombretipovisita= " + this.nombretipovisita + " - idtipovisita= " + this.idtipovisita + "]";
   }
   

   public void setNombretipovisita(java.lang.String nombretipovisita)
   {
      this.nombretipovisita = nombretipovisita;
   }

   public TipoVisita(java.lang.Long idtipovisita,
         java.lang.String nombretipovisita)
   {
      this.idtipovisita = idtipovisita;
      this.nombretipovisita = nombretipovisita;
   }

}